export default {
  SearchIcon: require('../assets/Svgs/Search.svg'),
  PlusIcon: require('../assets/Svgs/PlusIcon.svg'),
  MinusIcon: require('../assets/Svgs/MinusIcon.svg'),
  AllIcon: require('../assets/Svgs/All.svg'),
  BicycleIcon: require('../assets/Svgs/Electric.svg'),
  DriverIcon: require('../assets/Svgs/Road.svg'),
  MountainIcon: require('../assets/Svgs/Mountain.svg'),
  HelmentIcon: require('../assets/Svgs/Accessory.svg'),
  BicycleTabIcon: require('../assets/Svgs/Bicycle.svg'),
  OrangeBicycle: require('../assets/Svgs/OrangeBlackBicycle.svg'),
  HelmentImage: require('../assets/Svgs/helment.svg'),
  WhiteBicycle: require('../assets/Svgs/WhiteBicycle.svg'),
  BlackBicycle: require('../assets/Svgs/BlackBicycle.svg'),
  MapIcon: require('../assets/Svgs/map.fill.svg'),
  CartIcon: require('../assets/Svgs/cart.fill.svg'),
  PersonIcon: require('../assets/Svgs/person.fill.svg'),
  DocsIcon: require('../assets/Svgs/doc.text.fill.svg'),
  heartIcon: require('../assets/Svgs/Heart.svg'),
};
